spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: alusdkrudlwidg
    password: 75c2551e33d85e5db4b7ac44f85578dfb53ff0876cef438930ccabeefdd2d777
    url: jdbc:postgresql://ec2-52-4-104-184.compute-1.amazonaws.com:5432/d2auqjesn73ob2?sslmode=require
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true


